### ISSUE TITLE
Add Transmission client

### ISSUE THREAD

**Issue by vlotho** [NikolayIT/RatioMaster.NET#12]
hi,
this possible to Add Transmission client for windows & linux system ?

**Comment by vlotho** [comment]
i added this line into the TorrentClientFactory.cs file :
>		#region Transmission
		case "Transmission 2.82 (14160)":
		    {
			client.Name = "Transmission 2.82 (14160)">;
                        client.HttpProtocol = "HTTP/1.1";
                        client.HashUpperCase = false;
                        client.Key = GenerateIdString("hex", 8, false, true);
                        client.Headers = "User-Agent: Transmission/2.82_nl_Host: {host}_nl_Accept: */*_nl_Accept-Encoding: gzip;q=1.0, deflate, identity_nl_";
                        client.PeerID = "-TR2500-" + GenerateIdString("alphanumeric", 12, false, false);
                        client.Query = "info_hash={infohash}&amp;peer_id={peerid}&amp;port={port}&amp;uploaded={uploaded}&amp;downloaded={downloaded}&amp;left={left}&amp;numwant={numwant}&amp;key={key}&amp;compact=1&amp;supportcrypto=1{event}";
                        client.DefNumWant = 80;
                        // client.Parse = true;
                        client.SearchString = "&peer_id=-TR2500-";
                        client.ProcessName = "Transmission";
                        // client.StartOffset = 0;
                        // client.MaxOffset = 200000000;
                        break;
		    }
		#endregion

**Comment by NikolayIT** [comment]
Could you please create a pull request?

**Comment by vlotho** [comment]
I do not really know to use it ...
