### ISSUE TITLE
Not working with www/t411.ch

### ISSUE THREAD

**Issue by BobHD** [NikolayIT/RatioMaster.NET#20]
Hi,

RM was working really well with T411, but no longer: they seem to have found a way to detect its use, and ignore the fake uploads.

**Comment by Creadom** [comment]
Fellow member of T411 here, I actually have absolutely no issue using RatioMaster with the website. Fake uploads get added to my account with no issue. You just have to let the program send the update to the tracker before closing it, or you might lose up to 30 minutes of upload.

**Comment by BobHD** [comment]
Thanks for the tip, I'll try again and see if it was indeed an update problem.

I did not know what the update was for, that's useful information!

**Comment by BobHD** [comment]
Well, you're right, it's working now.

Not sure what happened, it must have been a fluke, Thanks!
